### ISSUE TITLE
`rake ar:create` fails with MySQL and models with `attr_*`

### ISSUE THREAD

**Issue by jbourassa** [padrino/padrino-framework#1265]
I found what appears to be a bug with Padrino 0.11. Creating a db with `rake ar:create`, the MySQL2 adapter and models with `attr_*` calls, ActiveRecord will try to connect to the database when loading the environment. This causes a crash since the database does not exist yet : we're trying to create it.

I'm not entirely sure this is a Padrino bug (rather than a bug with AR), but I have never expected such behaviour in Rails.

Here's how to reproduce :

```
padrino generate project pj -d activerecord -a mysql2
cd pj
bundle install

mkdir models
cat <<- EOF > models/whatnot.rb
class Whatnot < ActiveRecord::Base
  attr_protected :some_field
end
EOF

bundle exec rake ar:create
```

Stacktrace :

```
rake ar:create --trace
** Invoke ar:create (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
Unknown database 'pj_development'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `connect'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/mysql2-0.3.11/lib/mysql2/client.rb:44:in `initialize'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `new'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `mysql2_connection'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:223:in `table_exists?'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/attribute_methods/primary_key.rb:75:in `get_primary_key'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/attribute_methods/primary_key.rb:60:in `reset_primary_key'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/attribute_methods/primary_key.rb:49:in `primary_key'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activerecord-3.2.12/lib/active_record/attribute_assignment.rb:13:in `attributes_protected_by_default'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activemodel-3.2.12/lib/active_model/mass_assignment_security.rb:216:in `block in protected_attributes_configs'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activemodel-3.2.12/lib/active_model/mass_assignment_security.rb:188:in `yield'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activemodel-3.2.12/lib/active_model/mass_assignment_security.rb:188:in `protected_attributes'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activemodel-3.2.12/lib/active_model/mass_assignment_security.rb:118:in `block in attr_protected'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activemodel-3.2.12/lib/active_model/mass_assignment_security.rb:117:in `each'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activemodel-3.2.12/lib/active_model/mass_assignment_security.rb:117:in `attr_protected'
/Users/jbourassa/Desktop/pj/models/whatnot.rb:2:in `<class:Whatnot>'
/Users/jbourassa/Desktop/pj/models/whatnot.rb:1:in `<top (required)>'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `block in require'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:251:in `require'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/padrino-core-0.11.1/lib/padrino-core/reloader.rb:137:in `safe_load'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/padrino-core-0.11.1/lib/padrino-core/loader.rb:167:in `block in require_dependencies'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/padrino-core-0.11.1/lib/padrino-core/loader.rb:165:in `each'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/padrino-core-0.11.1/lib/padrino-core/loader.rb:165:in `require_dependencies'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/padrino-core-0.11.1/lib/padrino-core/loader.rb:72:in `block in load!'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/padrino-core-0.11.1/lib/padrino-core/loader.rb:72:in `each'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/padrino-core-0.11.1/lib/padrino-core/loader.rb:72:in `load!'
/Users/jbourassa/Desktop/pj/config/boot.rb:45:in `<top (required)>'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/padrino-core-0.11.1/lib/padrino-core/cli/rake_tasks.rb:13:in `require'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/padrino-core-0.11.1/lib/padrino-core/cli/rake_tasks.rb:13:in `block in <top (required)>'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `call'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:246:in `block in execute'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `each'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:241:in `execute'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:184:in `block in invoke_with_call_chain'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:205:in `block in invoke_prerequisites'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:203:in `each'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:203:in `invoke_prerequisites'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:183:in `block in invoke_with_call_chain'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/1.9.1/monitor.rb:211:in `mon_synchronize'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:177:in `invoke_with_call_chain'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/task.rb:170:in `invoke'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:143:in `invoke_task'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `each'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:101:in `block in top_level'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:110:in `run_with_threads'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:95:in `top_level'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:73:in `block in run'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:160:in `standard_exception_handling'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/lib/rake/application.rb:70:in `run'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/lib/ruby/gems/1.9.1/gems/rake-10.0.4/bin/rake:33:in `<top (required)>'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/bin/rake:23:in `load'
/Users/jbourassa/.rbenv/versions/1.9.3-p392-railsexpress/bin/rake:23:in `<main>'
Tasks: TOP => ar:create => environment
```

**Comment by sshaw** [comment]
Just got bit by this (again). Here's how to reproduce using ActiveRecord **3.2**: 

```
/tmp >padrino g project -d activerecord -a mysql2 padrino-migration-test
...
/tmp >cd padrino-migration-test/
/tmp/padrino-migration-test >bundle
...
/tmp/padrino-migration-test >padrino g model user age:integer name:string
...
/tmp/padrino-migration-test >perl -i -pE's/^\s*$/  attr_protected :age\n/' models/user.rb 
/tmp/padrino-migration-test >bundle exec padrino rake ar:create
=> Executing Rake ar:create ...
  ERROR -  Mysql2::Error - Unknown database 'padrino_migration_test_development':
 /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `connect'
/Users/sshaw/.rvm/gems/ruby-2.1.2/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `connect': Unknown database 'padrino_migration_test_development' (Mysql2::Error)
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `initialize'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `new'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/mysql2_adapter.rb:16:in `mysql2_connection'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:315:in `new_connection'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:325:in `checkout_new_connection'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:247:in `block (2 levels) in checkout'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `loop'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:242:in `block in checkout'
	from /Users/sshaw/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:239:in `checkout'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:102:in `block in connection'
	from /Users/sshaw/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:101:in `connection'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/model_schema.rb:224:in `table_exists?'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/attribute_methods/primary_key.rb:75:in `get_primary_key'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/attribute_methods/primary_key.rb:60:in `reset_primary_key'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/attribute_methods/primary_key.rb:49:in `primary_key'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activerecord-3.2.21/lib/active_record/attribute_assignment.rb:13:in `attributes_protected_by_default'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activemodel-3.2.21/lib/active_model/mass_assignment_security.rb:216:in `block in protected_attributes_configs'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activemodel-3.2.21/lib/active_model/mass_assignment_security.rb:188:in `yield'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activemodel-3.2.21/lib/active_model/mass_assignment_security.rb:188:in `protected_attributes'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activemodel-3.2.21/lib/active_model/mass_assignment_security.rb:118:in `block in attr_protected'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activemodel-3.2.21/lib/active_model/mass_assignment_security.rb:117:in `each'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activemodel-3.2.21/lib/active_model/mass_assignment_security.rb:117:in `attr_protected'
	from /private/tmp/padrino-migration-test/models/user.rb:2:in `<class:User>'
	from /private/tmp/padrino-migration-test/models/user.rb:1:in `<top (required)>'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `block in require'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:236:in `load_dependency'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/activesupport-3.2.21/lib/active_support/dependencies.rb:251:in `require'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/padrino-core-0.12.3/lib/padrino-core/reloader.rb:95:in `block in safe_load'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/padrino-core-0.12.3/lib/padrino-core/reloader.rb:300:in `with_silence'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/padrino-core-0.12.3/lib/padrino-core/reloader.rb:95:in `safe_load'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/padrino-core-0.12.3/lib/padrino-core/loader.rb:140:in `block in require_dependencies'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/padrino-core-0.12.3/lib/padrino-core/loader.rb:138:in `each'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/padrino-core-0.12.3/lib/padrino-core/loader.rb:138:in `require_dependencies'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/padrino-core-0.12.3/lib/padrino-core/loader.rb:58:in `load!'
	from /private/tmp/padrino-migration-test/config/boot.rb:46:in `<top (required)>'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/padrino-core-0.12.3/lib/padrino-core/cli/rake_tasks.rb:12:in `require'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/padrino-core-0.12.3/lib/padrino-core/cli/rake_tasks.rb:12:in `block in <top (required)>'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
	from /Users/sshaw/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
	from /Users/sshaw/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/padrino-core-0.12.3/lib/padrino-core/cli/base.rb:23:in `rake'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/gems/padrino-core-0.12.3/bin/padrino:9:in `<top (required)>'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/bin/padrino:23:in `load'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/bin/padrino:23:in `<main>'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sshaw/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

Now, if I remove `attr_protected`:

```
/tmp/padrino-migration-test >perl -i -pE's/attr_protected :age//' models/user.rb 
/tmp/padrino-migration-test >bundle exec padrino rake ar:create
=> Executing Rake ar:create ...
  DEBUG -   (1.4ms)  CREATE DATABASE `padrino_migration_test_development` DEFAULT CHARACTER SET `utf8` COLLATE `utf8_unicode_ci`
```
