### ISSUE TITLE
Unable to activate padrino-core-0.11.4, because activesupport-4.0.0 conflicts with activesupport (< 4.0, >= 3.1) (Gem::LoadError)

### ISSUE THREAD

**Issue by qichunren** [padrino/padrino-framework#1456]
```
➜  ~  padrino g project my_project -d datamapper -t riot -s jquery -e haml -m mocha
/Users/qichunren/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:1990:in `raise_if_conflicts': Unable to activate padrino-core-0.11.4, because activesupport-4.0.0 conflicts with activesupport (< 4.0, >= 3.1) (Gem::LoadError)
    from /Users/qichunren/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/specification.rb:1163:in `activate'
    from /Users/qichunren/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems.rb:181:in `rescue in try_activate'
    from /Users/qichunren/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems.rb:178:in `try_activate'
    from /Users/qichunren/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:109:in `rescue in require'
    from /Users/qichunren/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:35:in `require'
    from /Users/qichunren/.rvm/gems/ruby-1.9.3-p194/gems/padrino-gen-0.11.4/lib/padrino-gen.rb:2:in `<top (required)>'
    from /Users/qichunren/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/qichunren/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /Users/qichunren/.rvm/gems/ruby-1.9.3-p194/gems/padrino-gen-0.11.4/bin/padrino-gen:12:in `<main>'
➜  ~  ruby -v
ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin12.2.0]
➜  ~  gem -v
2.0.3
➜  ~  gem list

*** LOCAL GEMS ***

abstract (1.0.0)
actionmailer (4.0.0, 4.0.0.rc1, 3.2.14, 3.2.13, 3.2.12, 3.2.11, 3.2.9, 3.2.8, 3.2.4, 3.2.3, 3.0.16)
actionpack (4.0.0, 4.0.0.rc1, 3.2.14, 3.2.13, 3.2.12, 3.2.11, 3.2.9, 3.2.8, 3.2.4, 3.2.3, 3.0.16)
actionpack-action_caching (1.0.0)
active_support (3.0.0)
activemodel (4.0.0, 4.0.0.rc1, 3.2.14, 3.2.13, 3.2.12, 3.2.11, 3.2.9, 3.2.8, 3.2.4, 3.2.3, 3.0.16)
activerecord (4.0.0, 4.0.0.rc1, 3.2.14, 3.2.13, 3.2.12, 3.2.11, 3.2.9, 3.2.8, 3.2.4, 3.2.3, 3.0.16)
activerecord-deprecated_finders (1.0.3, 1.0.2, 0.0.3)
activerecord-uuid (0.9.1)
activeresource (3.2.14, 3.2.13, 3.2.12, 3.2.11, 3.2.9, 3.2.8, 3.2.4, 3.2.3, 3.0.16)
activesupport (4.0.0, 4.0.0.rc1, 3.2.14, 3.2.13, 3.2.12, 3.2.11, 3.2.9, 3.2.8, 3.2.4, 3.2.3, 3.0.17, 3.0.16, 3.0.0)
acts_as_list (0.2.0, 0.1.8)
acts_as_restful_list (0.6)
addressable (2.3.5, 2.3.3, 2.3.2, 2.2.7, 2.2.6)
albino (1.3.3)
amazon_flex_pay (0.9.13)
amq-client (0.9.5, 0.9.4)
amq-protocol (0.9.5, 0.9.4)
amqp (0.9.8, 0.9.7)
anjlab-bootstrap-rails (2.0.3.2)
annotate (2.5.0, 2.4.1.beta1, 2.4.0)
ansi (1.4.3)
api_taster (0.6.0, 0.2.0)
archive-tar-minitar (0.5.2)
arel (4.0.0, 3.0.2, 2.0.10)
arr-pm (0.0.8)
ast (1.1.0)
async-rack (0.5.1)
atomic (1.1.14, 1.1.13, 1.1.12, 1.1.10, 1.1.9, 1.1.8, 1.0.1)
audiojs (0.1.1)
audited (3.0.0)
audited-activerecord (3.0.0)
auto-space (0.0.2)
awesome_nested_set (2.1.5, 2.1.4)
awesome_print (1.1.0, 1.0.2, 0.4.0)
backports (3.3.1, 2.6.4, 2.6.2)
bcrypt-ruby (3.1.2, 3.1.1, 3.0.1)
better_errors (0.9.0, 0.7.2, 0.7.0)
binding_of_caller (0.7.2)
blankslate (2.1.2.4)
blather (0.8.5, 0.8.4)
bond (0.4.2)
bootstrap-datepicker-rails (1.0.0.3, 0.6.24, 0.6.17)
bootstrap-sass (2.3.2.2, 2.3.2.0, 2.3.1.3, 2.3.1.2, 2.3.1.0, 2.1.1.0, 2.1.0.1, 2.0.3.1, 2.0.3)
bootstrap-timepicker-rails (0.1.3)
bootstrap-will_paginate (0.0.3)
bootstrap_helper (1.4.1)
bootstrap_kaminari (0.0.3)
bourbon (1.4.0)
bourne (1.4.0, 1.1.2)
bson (1.8.5, 1.7.1, 1.6.2, 1.5.2)
bson_ext (1.6.2, 1.5.2)
builder (3.1.4, 3.0.4, 3.0.3, 3.0.0, 2.1.2)
bundler (1.3.4, 1.2.2, 1.2.1)
bunny (0.8.0, 0.7.9)
cabin (0.6.0)
cache_digests (0.2.0)
cancan (1.6.10, 1.6.9, 1.6.8, 1.6.7)
capistrano (2.15.5, 2.15.4, 2.14.2, 2.13.5, 2.12.0, 2.9.0, 2.6.0)
capybara (2.1.0, 2.0.3, 2.0.2, 2.0.1, 1.1.2, 0.4.1.2)
carrierwave (0.9.0, 0.8.0, 0.7.0, 0.6.2)
carrierwave-upyun (0.1.6, 0.1.5)
celerity (0.9.2)
cells (3.8.8)
celluloid (0.12.3)
cfoundry (0.4.9)
chef (10.14.4)
childprocess (0.3.9, 0.3.8, 0.3.7, 0.3.6, 0.3.5)
chinese_pinyin (0.4.2, 0.4.1)
choice (0.1.6)
chosen-rails (0.9.8.3, 0.9.8.2)
chronic (0.10.2, 0.9.1, 0.6.7)
chronic_duration (0.10.2)
chunky_png (1.2.8, 1.2.7, 1.2.6, 1.2.5, 1.2.1)
claide (0.3.2, 0.2.0)
clamp (0.6.0, 0.3.1)
classifier (1.3.3)
client_side_validations (3.2.1, 3.2.0.beta.6, 3.1.4)
client_side_validations-mongoid (2.4.0.beta.2)
clouseau (0.0.2)
cocoapods (0.24.0, 0.18.1, 0.17.0.rc5, 0.16.4, 0.16.0)
cocoapods-core (0.24.0, 0.18.1, 0.17.0.rc5)
cocoapods-downloader (0.2.0, 0.1.0)
codeigniter_vender (0.0.6)
coderay (1.0.9, 1.0.8, 1.0.7)
coffee-rails (4.0.0, 3.2.2)
coffee-script (2.2.0)
coffee-script-source (1.6.3, 1.6.2, 1.6.1, 1.4.0, 1.3.3, 1.3.1, 1.2.0)
colored (1.2)
columnize (0.3.6)
commonjs (0.2.6)
commonwatir (4.0.0)
compass (0.12.2, 0.11.7, 0.11.5)
compass-rails (1.0.3)
connection_pool (1.0.0, 0.9.2)
cookiejar (0.3.0)
cool.io (1.1.0)
crack (0.4.0, 0.3.2, 0.3.1)
cramp (0.15.1)
cucumber (1.3.2, 1.2.3, 1.2.2, 1.2.1)
cucumber-rails (1.3.1, 1.3.0)
culerity (0.2.15)
curb (0.8.4)
daemons (1.1.9, 1.0.10)
dalli (2.6.4, 2.6.2, 2.1.0, 1.1.1)
database_cleaner (1.0.1, 0.9.1, 0.8.0, 0.6.7)
debug_inspector (0.0.2)
debugger (1.4.0, 1.2.2, 1.2.0)
debugger-linecache (1.1.2)
debugger-ruby_core_source (1.2.0, 1.1.5, 1.1.3)
default_value_for (2.0.3, 2.0.1)
devise (3.1.1, 3.1.0, 3.0.1, 3.0.0, 2.2.4, 2.2.3, 2.1.2)
devise-encryptable (0.1.2, 0.1.1)
devise-i18n (0.5.9, 0.5.4)
diff-lcs (1.2.4, 1.2.1, 1.1.3)
directory_watcher (1.5.1, 1.4.0)
domain_name (0.5.7, 0.5.6)
durran-validatable (2.0.1)
em-hiredis (0.1.1)
em-http-request (1.0.3, 0.3.0)
em-http-server (0.1.4)
em-resolv-replace (1.1.3)
em-socksify (0.2.1)
em-synchrony (1.0.2)
em-websocket (0.5.0, 0.3.8)
email_spec (1.4.0, 1.2.1)
ember-rails (0.8.0)
enum_attr (1.0.2)
enumerize (0.6.1)
erubis (2.7.0, 2.6.6)
escape (0.0.4)
escape_utils (0.2.4)
eventmachine (1.0.3, 1.0.1, 1.0.0, 1.0.0.rc.4, 0.12.10)
eventmachine-le (1.1.5)
eventmachine_httpserver (0.2.1)
exception_notification (2.6.1)
execjs (2.0.2, 2.0.1, 1.4.0, 1.3.1, 1.2.9)
facebox-rails (0.2.0, 0.1.3, 0.1.2)
facter (1.6.14)
factory_girl (4.2.0, 4.1.0, 4.0.0, 3.5.0, 3.2.0, 2.3.2, 1.3.3)
factory_girl_rails (4.2.1, 4.2.0, 4.1.0, 4.0.0, 3.5.0, 3.2.0, 1.4.0, 1.0.1)
fakeweb (1.3.0)
faraday (0.8.7, 0.8.4, 0.7.6, 0.7.5)
faraday_middleware (0.9.0)
fast-stemmer (1.0.2, 1.0.0)
faye (0.8.3)
faye-rails (1.0.0)
faye-websocket (0.4.6)
femto-sqlite3 (1.3.7)
ffi (1.9.0, 1.4.0, 1.3.1, 1.2.0, 1.1.5, 1.0.11, 1.0.9)
figaro (0.6.4)
findme (0.0.8, 0.0.7, 0.0.5, 0.0.4, 0.0.3)
font-awesome-rails (3.2.1.2, 3.0.2.0, 0.4.1)
foreman (0.61.0, 0.60.2, 0.57.0, 0.53.0, 0.47.0)
formtastic (2.1.1)
fpm (0.4.36, 0.4.33)
fssm (0.2.10, 0.2.9, 0.2.7)
ftw (0.0.34)
garelic (0.0.2)
gem_plugin (0.2.3)
geminabox (0.10.1)
gherkin (2.12.0, 2.11.6, 2.11.1)
girl_friday (0.11.2)
glamazon (0.3.1)
globalize3 (0.0.11)
god (0.13.2)
gosu (0.7.48)
gravtastic (3.2.6)
growl (1.0.3)
guard (1.6.1, 1.3.3, 1.3.2, 1.2.3, 1.1.1)
guard-annotate (1.0.0)
guard-bundler (1.0.0, 0.1.3)
guard-livereload (1.0.3, 1.0.0)
guard-rspec (1.2.1, 0.3.1)
guard-shell (0.5.1)
guard-test (0.5.0)
haml (4.0.3, 4.0.2, 4.0.0, 3.1.8, 3.1.7, 3.1.6, 3.1.4, 3.1.2)
has_scope (0.5.1)
hash-deep-merge (0.1.1)
hashie (2.0.5, 2.0.3, 1.2.0)
heartbeat (0.0.2)
highlight_js-rails (0.0.2)
highline (1.6.19, 1.6.15, 1.6.13, 1.6.11, 1.6.8)
hike (1.2.3, 1.2.2, 1.2.1)
hirb (0.4.5)
hirb-unicode (0.0.4)
hiredis (0.4.5)
hpricot (0.8.6)
http-cookie (1.0.1)
http_accept_language (1.0.2)
http_parser.rb (0.5.3)
http_router (0.11.0, 0.10.2)
httpauth (0.2.0, 0.1)
httpclient (2.3.3)
i18n (0.6.5, 0.6.4, 0.6.1, 0.6.0, 0.5.0)
i18n-js (3.0.0.rc5, 2.1.2)
i18n_generators (1.2.1)
inherited_resources (1.3.1)
interact (0.5.0)
iobuffer (1.1.2)
ipaddress (0.8.0)
jasmine (1.3.1, 1.2.1)
jasmine-core (1.3.1, 1.2.0)
jbuilder (1.5.2, 1.5.1, 1.4.2, 1.0.2)
jekyll (0.12.1, 0.11.0)
journey (1.0.4, 1.0.3)
jquery-atwho-rails (0.1.6)
jquery-fileupload-rails (0.4.0, 0.3.4, 0.3.3)
jquery-rails (3.0.4, 3.0.1, 2.2.1, 2.2.0, 2.1.4, 2.1.3, 2.1.1, 2.0.2, 2.0.1)
jquery-turbolinks (2.0.0)
jquery-ui-rails (4.0.3, 4.0.2, 4.0.1, 2.0.2)
jQuery-Validation-Engine-rails (0.0.1)
jquery_mobile_rails (1.3.0)
json (1.8.0, 1.7.7, 1.7.6, 1.7.5, 1.7.4, 1.7.0, 1.6.1)
json_pure (1.6.7)
jwt (0.1.8, 0.1.5)
kaminari (0.14.1, 0.14.0, 0.13.0)
kgio (2.8.1, 2.8.0, 2.7.4, 2.6.0)
kramdown (1.2.0, 1.0.1, 0.14.2, 0.13.3)
launchy (2.3.0, 2.1.2, 2.1.0)
leshill-will_paginate (2.3.11)
less (2.2.2, 2.0.12)
less-rails (2.2.6, 2.1.8)
less-rails-bootstrap (2.2.1)
letter_opener (0.0.2)
librarian (0.0.25)
librevox (0.6)
libv8 (3.3.10.4 x86_64-darwin-12)
libwebsocket (0.1.6.1, 0.1.5)
linecache19 (0.5.13, 0.5.12)
liquid (2.5.0, 2.2.2)
listen (0.7.2, 0.6.0, 0.5.3, 0.5.0, 0.4.7, 0.4.4)
lumberjack (1.0.2)
mail (2.5.4, 2.5.3, 2.5.2, 2.4.4, 2.2.19)
manifests-vmc-plugin (0.4.17)
maruku (0.7.0, 0.6.1, 0.6.0)
md_emoji (0.0.6)
mechanize (2.7.1, 2.5.1)
memcache-client (1.8.5)
metaclass (0.0.1)
method_source (0.8.1, 0.8)
metro (0.3.4)
middleman (3.0.6)
middleman-core (3.0.6)
middleman-more (3.0.6)
middleman-sprockets (3.0.4)
mime-types (1.25, 1.23, 1.21, 1.19, 1.18)
mina (0.2.1)
mini_cache (1.0.0)
mini_magick (3.6.0, 3.3)
mini_portile (0.5.0)
minitest (4.7.5, 4.7.4, 4.6.1, 4.3.3, 4.3.2, 4.1.0, 3.3.0)
minitest-reporters (0.10.2)
mixlib-authentication (1.3.0)
mixlib-cli (1.2.2)
mixlib-config (1.1.2)
mixlib-log (1.4.1)
mixlib-shellout (1.1.0)
mobylette (3.3.2)
mocha (0.14.0, 0.13.3, 0.13.2, 0.10.5)
modular-scale (1.0.6, 1.0.2)
moneta (0.6.0)
mongo (1.8.5, 1.7.1, 1.6.2, 1.5.2)
mongoid (3.1.3, 3.1.1, 2.4.9, 1.0.6)
mongoid-rspec (1.8.2)
mongoid_auto_increment_id (0.6.2, 0.5.1)
mongoid_colored_logger (0.2.2)
mongoid_rails_migrations (1.0.0)
mongrel (1.2.0.pre2)
moped (1.5.0, 1.4.5, 1.4.2)
mothership (0.3.5)
multi_json (1.8.1, 1.8.0, 1.7.9, 1.7.8, 1.7.7, 1.7.4, 1.7.3, 1.7.2, 1.7.1, 1.6.1, 1.6.0, 1.5.0, 1.4.0, 1.3.7, 1.3.6, 1.0.4)
multi_xml (0.5.4, 0.4.1, 0.2.2)
multipart-post (1.2.0, 1.1.5, 1.1.4)
mysql2 (0.3.13, 0.3.11, 0.2.7)
nap (0.5.1)
net-http-digest_auth (1.2.1)
net-http-persistent (2.8)
net-ldap (0.3.1)
net-scp (1.1.2, 1.1.1, 1.0.4)
net-sftp (2.1.2, 2.0.5)
net-ssh (2.6.8, 2.6.7, 2.6.5, 2.6.2, 2.5.2, 2.3.0, 2.2.2, 2.2.1)
net-ssh-gateway (1.2.0, 1.1.0)
net-ssh-multi (1.1)
netrc (0.7.7)
newrelic_rpm (3.5.8.72)
niceogiri (1.1.1)
nokogiri (1.6.0, 1.5.8, 1.5.6, 1.5.5, 1.4.7)
ntlm-http (0.1.1)
numerizer (0.1.1)
oauth2 (0.9.1, 0.8.1, 0.8.0, 0.6.1, 0.5.1)
octokit (1.24.0, 1.19.0)
ohai (6.14.0)
oily_png (1.1.0)
oj (2.0.10)
omniauth (1.1.1, 1.1.0, 1.0.1)
omniauth-github (1.1.0, 1.0.1, 1.0.0)
omniauth-identity (1.1.0)
omniauth-oauth2 (1.1.1, 1.0.1, 1.0.0)
omniauth-qq (0.2.1)
omniauth-weibo-oauth2 (0.2.0)
open4 (1.3.0)
origin (1.1.0, 1.0.11)
orm_adapter (0.4.0)
padrino (0.11.4)
padrino-admin (0.11.4)
padrino-cache (0.11.4)
padrino-core (0.11.4, 0.10.7)
padrino-gen (0.11.4)
padrino-helpers (0.11.4, 0.10.7)
padrino-mailer (0.11.4)
parser (2.0.0.pre8)
pg (0.14.1)
polyamorous (0.5.0)
polyglot (0.3.3)
posix-spawn (0.3.6)
postmark (0.9.15)
postmark-rails (0.4.1)
powerbar (1.0.8)
powerpack (0.0.8)
preferences (0.4.2)
preforker (0.1.1)
promise (0.3.0)
pry (0.9.12.2, 0.9.11.4, 0.9.10)
pry-nav (0.2.3)
pry-rails (0.3.1, 0.3.0, 0.2.2, 0.2.1)
pry-stack_explorer (0.4.9)
puma (2.0.1, 1.6.3)
pure-rails (0.2.1)
pure-sass (0.0.4)
pusher (0.11.3)
pygments.rb (0.3.7, 0.1.3)
quiet_assets (1.0.2, 1.0.1)
rabel-meta (2.0, 1.5)
rabl (0.8.0, 0.7.9)
rack (1.5.2, 1.4.5, 1.4.1, 1.3.2, 1.2.5)
rack-cache (1.2)
rack-fiber_pool (0.9.2)
rack-livereload (0.3.8, 0.3.6)
rack-mount (0.8.3, 0.6.14)
rack-protection (1.5.0, 1.2.0)
rack-ssl (1.3.3, 1.3.2)
rack-stream (0.0.5)
rack-test (0.6.2, 0.6.1, 0.5.7)
rails (4.0.0, 4.0.0.rc1, 3.2.14, 3.2.13, 3.2.12, 3.2.11, 3.2.9, 3.2.8, 3.2.4, 3.2.3)
rails-erd (1.0.0)
rails-footnotes (3.7.9)
rails-i18n (0.7.0, 0.6.5, 0.6.3, 0.1.8)
rails-settings-cached (0.3.1, 0.2.2, 0.2.1)
rails3-jquery-autocomplete (1.0.10, 1.0.9)
rails_apps_composer (2.2.17)
rails_autolink (1.1.0, 1.0.9)
rails_config (0.3.1)
rails_uikit (0.0.1)
railties (4.0.0, 4.0.0.rc1, 3.2.14, 3.2.13, 3.2.12, 3.2.11, 3.2.9, 3.2.8, 3.2.4, 3.2.3, 3.0.16)
rainbow (1.1.4)
raindrops (0.12.0, 0.11.0, 0.10.0, 0.8.0)
rake (10.1.0, 10.0.4, 10.0.3, 10.0.2, 0.9.5, 0.9.2.2, 0.9.2)
ransack (0.7.0)
rb-fchange (0.0.5)
rb-fsevent (0.9.3, 0.9.2, 0.9.1)
rb-inotify (0.8.8)
rb-readline (0.4.2)
rdiscount (1.6.8)
rdoc (3.12.2, 3.12.1, 3.12)
redcarpet (2.3.0, 2.2.2, 2.1.1)
RedCloth (4.2.8)
redis (3.0.2, 2.2.2)
redis-namespace (1.2.1, 1.0.3)
redis-objects (0.5.2)
remotipart (1.0.5)
rename (0.0.9)
responders (0.9.3, 0.9.2)
resque (1.20.0)
resque-loner (1.2.1)
rest-client (1.6.7)
ripl (0.7.0)
ripl-multi_line (0.3.0)
ripl-rack (0.2.0)
rmagick (2.13.2)
rmmseg-cpp (0.2.9)
rouge (0.3.10, 0.3.2, 0.2.14)
rspec (2.13.0, 2.12.0, 2.11.0, 2.10.0)
rspec-cells (0.1.7, 0.1.2)
rspec-core (2.13.1, 2.13.0, 2.12.2, 2.12.0, 2.11.1, 2.10.0)
rspec-expectations (2.13.0, 2.12.1, 2.12.0, 2.11.3, 2.11.2, 2.10.0)
rspec-instafail (0.2.4)
rspec-mocks (2.13.1, 2.13.0, 2.12.2, 2.12.0, 2.11.3, 2.11.2, 2.10.1)
rspec-rails (2.13.2, 2.13.0, 2.12.2, 2.12.0, 2.11.4, 2.11.0, 2.10.1)
rubinius-actor (0.0.2)
rubinius-core-api (0.0.1)
rubocop (0.13.1)
ruby-debug-base19x (0.11.30.pre10)
ruby-debug-ide (0.4.17.beta14)
ruby-graphviz (1.0.8)
ruby_core_source (0.1.5)
ruby_gntp (0.3.4)
rubygems-bundler (1.1.0)
rubygems-update (2.0.3)
rubypants (0.2.0)
rubypython (0.5.1)
rubyzip (0.9.9)
rufus-scheduler (2.0.17)
rvm (1.11.3.5)
rvm-capistrano (1.2.2, 1.1.0)
safe_yaml (0.9.3)
sass (3.2.12, 3.2.10, 3.2.9, 3.2.8, 3.2.7, 3.2.6, 3.2.5, 3.2.3, 3.2.1, 3.1.20, 3.1.18, 3.1.17, 3.1.5)
sass-rails (4.0.0, 4.0.0.rc1, 3.2.6, 3.2.5, 3.2.3)
sassy-math (1.5, 1.2)
sdoc (0.3.20)
selenium-webdriver (2.33.0, 2.31.0, 2.30.0, 2.29.0, 2.26.0, 2.25.0)
sequel (3.48.0)
settingslogic (2.0.9, 2.0.6)
shotgun (0.9)
shoulda (3.3.2)
shoulda-context (1.0.1)
shoulda-matchers (1.5.6, 1.5.2, 1.4.2, 1.4.1, 1.2.0)
sidekiq (2.5.3)
signature (0.1.6)
simple_form (3.0.0, 3.0.0.rc, 2.1.0, 2.0.4, 2.0.2, 1.4.1)
simplecov (0.7.1)
simplecov-html (0.7.1)
simplecov-rcov (0.2.3)
sinatra (1.4.2, 1.3.6, 1.3.3, 1.3.2, 1.2.8, 1.2.6)
sinatra-can (0.2)
sinatra-contrib (1.3.1)
sinatra-flash (0.3.0)
sinatra-synchrony (0.4.1)
sinatra-websocket (0.1.2)
slim (2.0.1, 2.0.0, 1.3.9, 1.3.6)
slim-rails (2.0.1, 1.0.3)
slop (3.4.5, 3.4.3, 3.3.3, 3.3.2)
smarter_csv (1.0.10)
social-share-button (0.1.4, 0.1.0)
spork (1.0.0rc3)
sprite-factory (1.4.1)
sprockets (2.10.0, 2.9.3, 2.8.2, 2.8.1, 2.4.5, 2.2.2, 2.1.3)
sprockets-rails (2.0.0, 2.0.0.rc4, 2.0.0.rc2, 2.0.0.rc1)
sprockets-sass (0.8.0)
sqlite3 (1.3.8, 1.3.7, 1.3.6)
squeel (1.0.15, 1.0.13, 1.0.11)
streamio-ffmpeg (0.9.0)
stringex (1.3.0)
subexec (0.2.3, 0.1.0)
syntax (1.0.0)
sys-uname (0.9.0)
sys-uptime (0.6.1)
system-getifaddrs (0.2.0)
systemu (2.5.2)
temple (0.6.6, 0.6.5, 0.5.5)
test-unit (2.5.0)
therubyracer (0.10.2, 0.9.10)
thin (2.0.0.pre, 1.5.1, 1.5.0, 1.4.1, 1.3.1, 1.2.11)
thor (0.18.1, 0.18.0, 0.17.0, 0.16.0, 0.15.4, 0.14.6)
thread_safe (0.1.3, 0.1.2, 0.1.0)
tilt (1.4.1, 1.4.0, 1.3.7, 1.3.6, 1.3.5, 1.3.4, 1.3.3, 1.3.2)
timecop (0.6.1, 0.3.5)
timers (1.0.1)
torrent_api (0.2.8)
treetop (1.4.15, 1.4.14, 1.4.12, 1.4.11, 1.4.10)
tunnel-dummy-vmc-plugin (0.0.2)
turbo-sprockets-rails3 (0.3.2)
turbolinks (1.3.0, 1.2.0, 1.1.1, 0.5.1)
tux (0.3.0)
twitter-bootstrap-rails (2.0.3)
tzinfo (0.3.38, 0.3.37, 0.3.36, 0.3.35, 0.3.33)
uglifier (2.2.1, 2.1.2, 2.1.1, 2.1.0, 2.0.1, 1.3.0, 1.2.7, 1.2.4, 1.1.0)
unf (0.0.5)
unf_ext (0.0.6, 0.0.5)
unicode-display_width (0.1.1)
unicorn (4.6.3, 4.6.2, 4.2.1, 4.2.0)
unicorn-rails (1.1.0)
url_mount (0.2.1)
uuidtools (2.1.3)
vcr (2.2.5)
vegas (0.1.11)
version_fu (1.0.1)
versionist (1.0.0, 0.3.1)
vines (0.4.5)
vmc (0.4.5)
warden (1.2.3, 1.2.1)
watir (4.0.2)
watir-webdriver (0.6.2)
webmock (1.12.3, 1.8.11)
webrobots (0.1.0, 0.0.13)
websocket (1.0.7, 1.0.4)
weibo_2 (0.1.4)
whenever (0.8.4, 0.8.2, 0.7.3)
will_paginate (3.0.4, 3.0.3, 3.0.2)
will_paginate-bootstrap (0.2.2)
wmd-rails (0.0.7)
wombat (2.1.0)
xcodeproj (0.10.1, 0.5.5, 0.5.2, 0.4.0)
xml-simple (1.1.1)
xmpp4r (0.5)
xpath (2.0.0, 1.0.0, 1.0.0.beta1, 0.1.4)
yajl-ruby (1.1.0)
yard (0.8.3, 0.8.2.1)
zurb-foundation (4.3.1, 4.0.9, 3.2.5, 3.2.3)
```

**Comment by vinayvihari** [comment]
Unable to activate run_loop-2.4.1, because json-2.0.2 conflicts with json (~> 1.8) (Gem::ConflictError)
/Users/adtechadmin1/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2288:in `raise_if_conflicts'
/Users/adtechadmin1/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1408:in `activate'
/Users/adtechadmin1/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1442:in `block in activate_dependencies'
/Users/adtechadmin1/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1428:in `each'
/Users/adtechadmin1/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1428:in `activate_dependencies'
/Users/adtechadmin1/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:1410:in `activate'
/Users/adtechadmin1/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems.rb:220:in `rescue in try_activate'
/Users/adtechadmin1/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems.rb:213:in `try_activate'
/Users/adtechadmin1/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
/Users/adtechadmin1/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:40:in `require'
/Users/adtechadmin1/Documents/OnMe/features/support/env.rb:5:in `<top (required)>'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/rb_support/rb_language.rb:96:in `load_code_file'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:142:in `load_file'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:84:in `block in load_files!'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `each'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime/support_code.rb:83:in `load_files!'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:253:in `load_step_definitions'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/runtime.rb:61:in `run!'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/lib/cucumber/cli/main.rb:32:in `execute!'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/gems/cucumber-2.4.0/bin/cucumber:8:in `<top (required)>'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/bin/CUCUMBER:22:in `load'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/bin/CUCUMBER:22:in `<main>'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/Users/adtechadmin1/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by vinayvihari** [comment]
Unable to activate run_loop-2.4.1, because json-2.0.2 conflicts with json (~> 1.8) (Gem::ConflictError)

**Comment by sandyfox** [comment]
Unable to activate knife-solo-0.6.0, because net-ssh-4.1.0 conflicts with net-ssh (< 4.0, >= 2.7) (Gem::ConflictError)

**Comment by onlytapas** [comment]
Unable to activate run_loop-2.4.1, because json-2.0.2 conflicts with json (~> 1.8) (Gem::ConflictError)
/Users/tesco/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/specification.rb:2288:in `raise_if_conflicts'

**Comment by neobie** [comment]
Unable to activate faraday_middleware-0.10.0, because faraday-0.12.2 conflicts with faraday
what is this?

**Comment by vuppalashiva** [comment]
Unable to activate run_loop-2.6.0, because json-2.0.2 conflicts with json (~> 1.8) (Gem::ConflictError).
Am using ruby 2.4.0.

Anybody has any clue why is this happening ?

**Comment by jaywantkhedkar** [comment]
Unable to activate run_loop-2.6.1, because json-2.0.2 conflicts with json (~> 1.8) (Gem::ConflictError)
 I am using ruby 2.4.0.

Any one know why this error come .

**Comment by goshgarh** [comment]
Unable to activate unirest-1.1.2, because json-2.0.4 conflicts with json (~> 1.8.1) (Gem::ConflictError)

Anyone knows why is this happening?
