### ISSUE TITLE
error occurred when I modify source code (padrino is running)

### ISSUE THREAD

**Issue by ssut** [padrino/padrino-framework#1662]
```
  ERROR -  ActiveSupport::Concern::MultipleIncludedBlocks - Cannot define multiple 'included' blocks for a Concern:
 /home/ssut/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0/lib/active_support/concern.rb:126:in `included'
  ERROR -  Failed to load /home/ssut/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0/lib/active_support/logger_silence.rb; removing partially defined constants
  ERROR -  ActiveSupport::Concern::MultipleIncludedBlocks - Cannot define multiple 'included' blocks for a Concern:
 /home/ssut/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.0/lib/active_support/concern.rb:126:in `included'
```

An error occurred when I modify source code. *prerequisite: padrino is running and reload option is on.

**Comment by senekis** [comment]
I'm getting the same error but I'm not using an external library.

I have a module that extend ActiveSupport::Concern and is included into a model. I created a dummy project here: https://github.com/senekis/dashboard to reproduce the error.

Steps to reproduce:
1. Starts the padrino application
2. Open / in a browser
3. Modify the file: user_mixins/filters.rb
4. Reload / in the browser

You'll see the error ActiveSupport::Concern::MultipleIncludedBlocks - Cannot define multiple 'included' blocks for a Concern:

I appreciate your help

**Comment by ujifgc** [comment]
Should be fixed on master by d25298caba28bf7a7157bd7475736ad129365525

**Comment by ujifgc** [comment]
The fix broke reloading apps. Reverted it.

Temporary solution: don't use `ActiveSupport::Concern` and other techniques dependent on mutating module instance variables.

**Comment by u007** [comment]
👍  faced the same issue,
i guess since production no reload, it should work, but on development, we need to restart on concern change

**Comment by u007** [comment]
from my finding, adding this in my concern file
Object.send(:remove_const, :<ConcernClass>) if Object.constants.include?(:<ConcernClass>)

fix the issue, but some how the model class that include this concern class will need to reload too...
otherwise the model class will be using the old concern (havent reload ConcernClass module)

**Comment by u007** [comment]
i tried to remove activeconcern from my concerns/tokenable.rb
but i realize, when i modify this file, the actual file that include this file will not reload
Example:
```
# ruby way
module Tokenable
  def self.included(klass)
    klass.before_validation :yahoo
  end

  def yahoo
    puts "aaaaa"
    self.token = "aaaaa"
  end
```

# model
class Aaa < ActiveRecord::Base
  include Tokenable

end
```
when i run in padrino console,
i modified file concerns/tokenable.rb and change my up and token assignment to "bbbb",
then i ran reload!
and Tried 
```
row = Aaa.new
row.valid?
# output "aaaaa"
# expected "bbbb"
```

**Comment by u007** [comment]
okay, ive a fix,
can someone verify that this works with few rspec? :)

https://gist.github.com/u007/47b2f021670d54f862624ae70494a085

**Comment by debbbbie** [comment]
> okay, ive a fix,
> can someone verify that this works with few rspec? :)
> 
> it detects reloading of concern file, then find all models that include the file,
> and try to locate the file for reload, and remove the constant from session,
> and finally load it in the end
> 
> https://gist.github.com/u007/47b2f021670d54f862624ae70494a085

It works, thanks!
