### ISSUE TITLE
:zh_CN is not a valid locale

### ISSUE THREAD

**Issue by JuoCode** [padrino/padrino-framework#1864]
I add following in `boot.rb`

```
Padrino.before_load do
  I18n.locale = 'zh_CN'.to_sym
end
```

Got following error:

```
/Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/i18n-0.7.0/lib/i18n.rb:284:in `enforce_available_locales!': :zh_CN is not a valid locale (I18n::InvalidLocale)
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/i18n-0.7.0/lib/i18n/config.rb:13:in `locale='
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/i18n-0.7.0/lib/i18n.rb:35:in `locale='
  from /Users/juo/workspace/my_project/config/boot.rb:38:in `block in <top (required)>'
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/padrino-core-0.12.4/lib/padrino-core/loader.rb:57:in `call'
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/padrino-core-0.12.4/lib/padrino-core/loader.rb:57:in `each'
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/padrino-core-0.12.4/lib/padrino-core/loader.rb:57:in `load!'
  from /Users/juo/workspace/my_project/config/boot.rb:47:in `<top (required)>'
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/padrino-core-0.12.4/lib/padrino-core/cli/launcher.rb:25:in `require'
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/padrino-core-0.12.4/lib/padrino-core/cli/launcher.rb:25:in `start'
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/gems/padrino-core-0.12.4/bin/padrino:9:in `<top (required)>'
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/bin/padrino:23:in `load'
  from /Users/juo/.rvm/gems/ruby-2.0.0-p247/bin/padrino:23:in `<main>'
```

**Comment by ujifgc** [comment]
You should add `'zh_CN'` to `I18n.available_locales`. Also, Google helps.

**Comment by JuoCode** [comment]
Sorry, it should be `zh_cn`, Thanks
