### ISSUE TITLE
ArgumentError happen in padrino-edge controller with 'provides' and 'block parameter'

### ISSUE THREAD

**Issue by tune** [padrino/padrino-framework#1868]
Is this a bug or usage has changed?

### My environment

```
% ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [i386-mingw32]
```

### Problem code

https://github.com/tune/padrino_sample/tree/parameter_block

```
Sample::App.controllers :sample do
  get '/:param1/:param2', provides: :text do |param1, param2|
    "param1:#{param1} param2:#{param2}"
  end
end

```

### Padrino Stable Gem (0.12.4)

http://localhost:3000/sample/foo/bar
  => param1:foo param2:bar

### Padrino Edge (github master)

```txt
ArgumentError - wrong number of arguments (3 for 2):
        C:/repos/OSS/padrino_sample/app/controllers/sample.rb:3:in `block (2 levels) in <top (required)>'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/application/routing.rb:502:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/application/routing.rb:502:in `block in route'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/application/routing.rb:970:in `[]'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/application/routing.rb:970:in `block in invoke_route'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/application/routing.rb:965:in `catch'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/application/routing.rb:965:in `invoke_route'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/application/routing.rb:931:in `block in route!'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/path_router/compiler.rb:56:in `block in call_by_request'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/path_router/compiler.rb:87:in `block in rotation'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/path_router/compiler.rb:86:in `loop'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/path_router/compiler.rb:86:in `with_object'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/path_router/compiler.rb:86:in `rotation'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/path_router/compiler.rb:52:in `call_by_request'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/path_router.rb:43:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/application/routing.rb:928:in `route!'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/application/routing.rb:911:in `block in dispatch!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/application/routing.rb:909:in `dispatch!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/head.rb:13:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/methodoverride.rb:22:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/reloader/rack.rb:22:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/logger.rb:452:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/application/show_exceptions.rb:9:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/router.rb:84:in `block in call'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/router.rb:75:in `each'
        C:/Ruby21/lib/ruby/gems/2.1.0/bundler/gems/padrino-framework-5d79fdfb5dae/padrino-core/lib/padrino-core/router.rb:75:in `call'
        C:/Ruby21/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
        C:/Ruby21/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'        C:/Ruby21/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
        C:/Ruby21/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by ujifgc** [comment]
Confirmed a bug, but not on exactly that versions. Your Gemfile is requiring master branch of Padrino from github, that's not 0.12.4 but 0.12.0.rc1 and unreleased yet.

0.12.4: `get '/:param1/:param2', provides: :text do  |param1, param2|` captures params into param1 and param2 variable

0.13.0.rc1: `get '/:param1/:param2', provides: :text do  |param1, param2|` generated the ArgumentError

**Comment by namusyaka** [comment]
In 0.12.4 (with http_router), the arity was changed by request every time.
please see the following code.
```ruby
get "/foo/:id/", provides: :html do |id, format|
  "#{id}, #{format}"
end

get "/foo/123.html" #=> "123, html"
get "/foo/123" #=> ArgumentError
```

Current behavior:
```ruby
get "/foo/123.html" #=> "123, html"
get "/foo/123" #=> "123, "
```

I think this behavior shouldn't be respected by the new router.

**Comment by ujifgc** [comment]
@namusyaka do you think it should be a sensible exception or a warning at compile time if a user forgets to match number of captures in route path to the number of block arguments? I think adding and removing captures at run time is not very good solution.

**Comment by namusyaka** [comment]
Hmm, good point. I agree.
However, I've got a question. 
Maybe many people don't know about the `format` parameter.
If the `provides` parameter is enabled, Which is better solution?

 1. Matches real number of captures including `format` parameter.
 2. Matches the number of captures except `format` parameter.

**Comment by ujifgc** [comment]
Parameter `:provides` is Sinatra legacy and it does more in Padrino. I think it's misnamed and should be named `:format`.

As for arity matching, I think we should be including `format` parameter. It should not confuse users as it would bark at compile time and provide a sensible message. Also, if we remove `format` from capturing we should also be removing `:with` captures with the same reasoning.

On the other hand with the router we have now we could deprecate all these path-tampering options. It could remove an enormous amount of code from `routing.rb`.

@padrino/core-members need educated opinions!

**Comment by namusyaka** [comment]
>>Parameter :provides is Sinatra legacy and it does more in Padrino. I think it's misnamed and should be named :format.

:+1: 

>>As for arity matching, I think we should be including format parameter. It should not confuse users as it would bark at compile time and provide a sensible message.

:+1:

>>On the other hand with the router we have now we could deprecate all these path-tampering options. It could remove an enormous amount of code from routing.rb.

I totally agree with you :+1:
 
Also see [Sinatra 2.0](https://gist.github.com/rkh/468571242a544df5eeb5)

**Comment by ujifgc** [comment]
Closing as fixes. We will probably revisit this later.
