### ISSUE TITLE
Unexpected error while processing request: undefined method `join'

### ISSUE THREAD

**Issue by lidashuang** [padrino/padrino-framework#1875]
Padrino version is v. 0.12.4
the project source: https://github.com/lidashuang/wx_padrino
ruby 2.2.0

I use this command init the project:

```
$ padrino g project wx -d activerecord -a postgres -t minitest -s jquery -e erb -c sass
```

but when run by 

```
bundle exec padrino start 
```

```
Unexpected error while processing request: undefined method `join' for #<String:0x007f9bb3d632f0>
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:37:in `rescue in call'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/show_exceptions.rb:21:in `call'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/padrino-core-0.12.4/lib/padrino-core/router.rb:84:in `block in call'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/padrino-core-0.12.4/lib/padrino-core/router.rb:75:in `each'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/padrino-core-0.12.4/lib/padrino-core/router.rb:75:in `call'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in `call'
	/Users/lds/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:1046:in `block in spawn_threadpool'
```

**Comment by ujifgc** [comment]
Try to add `gem 'rack', '~> 1.5.0'` to your Gemfile.

**Comment by CyberFerret** [comment]
I am having a problem deploying my new Padrino projects to Amazon's Elastic Beanstalk at the moment.  The Puma logs are showing:

[2325] + Gemfile in context: /var/app/current/Gemfile
/opt/rubies/ruby-2.0.0-p598/lib/ruby/gems/2.0.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:34:in `block in setup': You have already activated rack 1.6.0, but your Gemfile requires rack 1.5.3. 

It appears that the EC2 environment installs Rack 1.6.0.  I've tried specifying Rack 1.5.3 in my Gemfile, as well as doing a 'bundle package' to contain all gems within my deployment package, but to no avail.
