### ISSUE TITLE
"NoMethodError: undefined method `[]' for nil:NilClass" when running rake ar:drop or ar:create

### ISSUE THREAD

**Issue by krukgit** [padrino/padrino-framework#1879]
I've taken over a project written in Padrino (0.12.3, ruby 2.1.2). When trying to create a database I kept running into a problem:

```
NoMethodError: undefined method `[]' for nil:NilClass
/Users/me/.rvm/gems/ruby-2.1.2@gemset/gems/padrino-gen-0.12.3/lib/padrino-gen/padrino-tasks/activerecord.rb:61:in `rescue in create_database'
/Users/me/.rvm/gems/ruby-2.1.2@gemset/gems/padrino-gen-0.12.3/lib/padrino-gen/padrino-tasks/activerecord.rb:40:in `create_database'
/Users/me/.rvm/gems/ruby-2.1.2@gemset/gems/padrino-gen-0.12.3/lib/padrino-gen/padrino-tasks/activerecord.rb:36:in `block (2 levels) in <top (required)>'
/Users/me/.rvm/gems/ruby-2.1.2@gemset/bin/ruby_executable_hooks:15:in `eval'
/Users/me/.rvm/gems/ruby-2.1.2@gemset/bin/ruby_executable_hooks:15:in `<main>'
NoMethodError: undefined method `[]' for nil:NilClass
/Users/me/.rvm/gems/ruby-2.1.2@gemset/gems/padrino-gen-0.12.3/lib/padrino-gen/padrino-tasks/activerecord.rb:41:in `create_database'
/Users/me/.rvm/gems/ruby-2.1.2@gemset/gems/padrino-gen-0.12.3/lib/padrino-gen/padrino-tasks/activerecord.rb:36:in `block (2 levels) in <top (required)>'
/Users/me/.rvm/gems/ruby-2.1.2@gemset/bin/ruby_executable_hooks:15:in `eval'
/Users/me/.rvm/gems/ruby-2.1.2@gemset/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => ar:create
```

Looking through `padrino-tasks/activerecord.rb` I traced the error to this block:

```
task :create => :environment do
  create_database(ActiveRecord::Base.configurations[Padrino.env])
end
```

`ActiveRecord::Base.configurations` is a hash, with string keys, `Padrino.env` is a symbol, so the config ends up being `nil`. 

I temporarily overwrote `ActiveRecord::Base.configurations` with `ActiveRecord::Base.configurations.with_indifferent_access` and it's working fine but I'd appreciate a proper fix.

**Comment by marcuxyz** [comment]
I am opening this `issue` again, as the problem is occurring with me too.

After running the command to create the project:

`$ padrino g project todo -t rspec -d activerecord -e slim`

I run the command to generate a controller 

`padrino g controller Home`

and the error occurs: 

```shell
=> Problem loading ./config/boot.rb
=> undefined method `[]=' for #<ActiveRecord::DatabaseConfigurations:0x000000000353b210>
Did you mean?  []
```

My boot.rb file:


```ruby
RACK_ENV = ENV['RACK_ENV'] ||= 'development' unless defined?(RACK_ENV)
PADRINO_ROOT = File.expand_path('../..', __FILE__) unless defined?(PADRINO_ROOT)

require 'bundler/setup'
Bundler.require(:default, RACK_ENV)

Padrino.dependency_paths.unshift Padrino.root('config/initializers/*.rb')

Padrino.before_load do
end

Padrino.after_load do
end

Padrino.load!
```
