### ISSUE TITLE
Padrino Generator not working

### ISSUE THREAD

**Issue by AlexWayfer** [padrino/padrino-framework#1955]
Arch Linux, ruby 2.2.2p95
```bash
~/Documents/ruby/padrino $ padrino g project myapp -d datamapper -b
/home/alex/.gem/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/ordered_hash.rb:3:in `<top (required)>': undefined method `add_builtin_type' for Psych:Module (NoMethodError)
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:121:in `require'
        from /home/alex/.gem/ruby/2.2.0/gems/padrino-gen-0.12.5/lib/padrino-gen.rb:4:in `<top (required)>'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/alex/.gem/ruby/2.2.0/gems/padrino-gen-0.12.5/bin/padrino-gen:12:in `<main>'
```

**Comment by ujifgc** [comment]
Closing as resolved by reinstalling ruby stack.
