### ISSUE TITLE
Padrino 12.5 + Ruby 2.3 + ActiveRecord 3.2.22 = ActiveRecord::ConnectionNotEstablished Error

### ISSUE THREAD

**Issue by sshaw** [padrino/padrino-framework#2026]
Here's [the Gemfile](https://github.com/sshaw/itunes_store_transporter_web/blob/9fb51ec8fc006772baa2449884ec2ac2f0ec41e2/Gemfile), and the error:
```
~/code/ruby/itunes_store_transporter_web >!r
ruby -v && padrino c
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin13]
/Users/sshaw/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_pool.rb:410:in `retrieve_connection': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_specification.rb:171:in `retrieve_connection'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22/lib/active_record/connection_adapters/abstract/connection_specification.rb:145:in `connection'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22/lib/active_record/model_schema.rb:224:in `table_exists?'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/activerecord-3.2.22/lib/active_record/base.rb:423:in `inspect'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.12.5/lib/padrino-core/reloader.rb:77:in `to_s'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.12.5/lib/padrino-core/reloader.rb:77:in `block in lock!'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-support-0.12.5/lib/padrino-support/core_ext/object_space.rb:19:in `block in classes'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-support-0.12.5/lib/padrino-support/core_ext/object_space.rb:17:in `each_object'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-support-0.12.5/lib/padrino-support/core_ext/object_space.rb:17:in `each'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-support-0.12.5/lib/padrino-support/core_ext/object_space.rb:17:in `classes'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.12.5/lib/padrino-core/reloader.rb:76:in `lock!'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.12.5/lib/padrino-core/loader.rb:56:in `load!'
	from /Users/sshaw/code/ruby/itunes_store_transporter_web/config/boot.rb:39:in `<top (required)>'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.12.5/lib/padrino-core/cli/base.rb:37:in `require'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.12.5/lib/padrino-core/cli/base.rb:37:in `console'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/gems/padrino-core-0.12.5/bin/padrino:9:in `<top (required)>'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/bin/padrino:23:in `load'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/bin/padrino:23:in `<main>'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/sshaw/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

Now, using Ruby 2.2.3:
```
~/code/ruby/itunes_store_transporter_web >rvm 2.2.3
~/code/ruby/itunes_store_transporter_web >padrino c
  DEBUG -  TransporterConfig Load (0.1ms)  SELECT "config".* FROM "config" LIMIT 1
=> Loading development console (Padrino v.0.12.5)
=> Loading Application ItunesStoreTransporterWeb
padrino [0.12.5] (itunes_store_transporter_web)$
```
Here's [the Padrino code](https://github.com/padrino/padrino-framework/blob/0.12.5/padrino-core/lib/padrino-core/reloader.rb#L77) that causes the problem. Seems like an odd thing to have to do.

**Comment by nesquena** [comment]
cc @ujifgc @namusyaka
