### ISSUE TITLE
NameError - uninitialized constant ActiveSupport::Deprecation

### ISSUE THREAD

**Issue by federicolucca** [padrino/padrino-framework#2062]
hi,

The mailer works fine before the change of the server host.Could be a problem with the ruby version on the new host?

Thanks
```
App 8613 stderr: 2016-07-12 09:53:11 - NameError - uninitialized constant ActiveSupport::Deprecation
App 8613 stderr: Did you mean?  ActiveSupport::Duration:
App 8613 stderr: 	/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/core_ext/module/aliasing.rb:27:in 'alias_method_chain'
App 8613 stderr: 	/usr/local/lib/ruby/gems/2.3.0/gems/padrino-mailer-0.13.0/lib/padrino-mailer/ext.rb:26:in '<class:Message>'
App 8613 stderr: 	/usr/local/lib/ruby/gems/2.3.0/gems/padrino-mailer-0.13.0/lib/padrino-mailer/ext.rb:4:in '<module:Mail>'
App 8613 stderr: 	/usr/local/lib/ruby/gems/2.3.0/gems/padrino-mailer-0.13.0/lib/padrino-mailer/ext.rb:3:in '<top (required)>'
App 8613 stderr: 	/usr/local/lib/ruby/gems/2.3.0/gems/padrino-mailer-0.13.0/lib/padrino-mailer.rb:45:in 'require'
App 8613 stderr: 	/usr/local/lib/ruby/gems/2.3.0/gems/padrino-mailer-0.13.0/lib/padrino-mailer.rb:45:in 'block in registered'
App 8613 stderr: 	/usr/local/lib/ruby/gems/2.3.0/gems/padrino-mailer-0.13.0/lib/padrino-mailer/helpers.rb:137:in 'email'
App 8613 stderr: 	/usr/local/lib/ruby/gems/2.3.0/gems/padrino-mailer-0.13.0/lib/padrino-mailer/helpers.rb:30:in 'email'
App 8613 stderr: 	/var/www/dev/admin/app.rb:73:in 'sendEmailDirect'
```

**Comment by ujifgc** [comment]
Fixed in Padrino 0.13.2 by da54bef74d48db154ca1c1a5150aac4391165217
