### ISSUE TITLE
NoMethodError - undefined method `key' for Account:Class

### ISSUE THREAD

**Issue by jorgefuertes** [padrino/padrino-framework#2068]
Upgrading to padrino 0.13.2 gives this issue with any model, how if doesn't knows methods like many, key, timestamps...

Using padrino 0.13.2, ruby 2.3.1.

```
$> padrino -v
Padrino v. 0.13.2
$> rvm list
rvm rubies
 * ruby-2.3.1 [ x86_64 ]
```
Steps to reproduce:

```
# Tried with several options, like no test framework or no sass.
$> padrino gen project mytest -d mongomapper -t minitest -e slim -c sass
$> cd mytest
$> bundle
$> padrino gen admin
$> padrino s

WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
  DEBUG -  MONGODB [DEBUG] Logging level is currently :debug which could negatively impact client-side performance. You should set your logging level no lower than :info in production.
  DEBUG -
  ERROR -  NoMethodError - undefined method `key' for Account:Class:
 ~/mytest/models/account.rb:6:in `<class:Account>'
~/mytest/models/account.rb:6:in `<class:Account>': undefined method `key' for Account:Class (NoMethodError)
```

Maybe my fault, but I can't find a reason, and happens every time, with old and new projects.

Thanks in advance.

Gemfile:
```
source 'https://rubygems.org'

# Padrino supports Ruby version 1.9 and later
# ruby '2.3.1'

# Distribute your app as a gem
# gemspec

# Server requirements
# gem 'thin' # or mongrel
# gem 'trinidad', :platform => 'jruby'

# Optional JSON codec (faster performance)
# gem 'oj'

# Project requirements
gem 'rake'

# Component requirements
gem 'bcrypt'
gem 'sass'
gem 'slim'
gem 'bson_ext', :require => 'mongo'
gem 'mongo_mapper'

# Test requirements
gem 'minitest', '~> 5.1', :require => 'minitest/autorun', :group => 'test'
gem 'rack-test', :require => 'rack/test', :group => 'test'

# Padrino Stable Gem
gem 'padrino', '0.13.2'

# Or Padrino Edge
# gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core support gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.13.2'
# end

```

**Comment by namusyaka** [comment]
@jorgefuertes Hi, thanks for your report.
I confirmed the problem. I'll fix it in a few days.
Btw, you can avoid the problem by adding `gem 'activesupport', '~> 4.2.0'` to your Gemfile and executing re`bundle install`
