### ISSUE TITLE
NoMethodError - undefined method `indifferent_params' with sinatra v2.0.0

### ISSUE THREAD

**Issue by sue445** [padrino/padrino-framework#2132]
#### Do you want to request a *feature* or report a *bug*?
bug

#### What is the current behavior?

Gemfile

```ruby
gem "padrino", "0.14.0.1"
gem "sinatra", "2.0.0"
```

When boot padrino and access any action, padrino is crashed!

```
bundle exec padrino s

(snip)

2017-05-08 01:00:17 - NoMethodError - undefined method `indifferent_params' for #<Sebastian::App:0x007fb6600492f0>:
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/padrino-core-0.14.0.1/lib/padrino-core/application/routing.rb:933:in `dispatch!'
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `invoke'
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `call!'
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:913:in `call'
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rollbar/middleware/rack.rb:20:in `block in call'
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rollbar.rb:145:in `scoped'
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/rollbar-2.14.1/lib/rollbar/middleware/rack.rb:18:in `call'
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/lib/connection_pool_management_middleware.rb:7:in `block in call'
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:408:in `with_connection'
	/Users/sue445/dev/workspace/github.com/sue445/sebastian-badge/lib/connection_pool_management_middleware.rb:7:in `call'
```

#### What is the expected behavior?
no error

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

* Ruby: 2.4.1
* Padrino: 0.14.0.1
* Sinatra: 2.0.0
* Rack: 2.0.1
* OS: OSX 10.9.5

> Did this work in previous versions?

Sinatra 2.0.0.rc2 is no problem. 

I think this is affecting.
https://github.com/sinatra/sinatra/pull/1279

**Comment by ujifgc** [comment]
Thank you for your report.

**Comment by vuhailuyen1991** [comment]
Same issue after upgrading sinatra to 2.0

**Comment by faustoct** [comment]
Any idea when to add padrino on top of more recent sinatra version ?

**Comment by wikimatze** [comment]
Hi @faustoct, we have to checkout what is failing and then try to use the version in a further release.

**Comment by faustoct** [comment]
hash problems accessing hash in post request through params as described 
 here https://stackoverflow.com/questions/14540729/how-do-i-map-an-application-json-post-request-to-the-params-in-rails

**Comment by faustoct** [comment]
working now padrino 0.14.0.2
