### ISSUE TITLE
new created pradrino project show errors

### ISSUE THREAD

**Issue by jiyaping** [padrino/padrino-framework#2143]
Hi, I have created a padrino project and run padrino start command, visit the http://127.0.0.1:3000, show following errors:

```
[2017-06-07 23:09:05] INFO  WEBrick 1.3.1
[2017-06-07 23:09:05] INFO  ruby 2.2.4 (2015-12-16) [i386-mingw32]
[2017-06-07 23:09:05] INFO  WEBrick::HTTPServer#start: pid=1112 port=3000
2017-06-07 23:09:10 - NoMethodError - undefined method `indifferent_params' for #<Testest::App:0x44cbe18>:
        d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/padrino-core-0.13.3.2/lib/padrino-core/application/routing.rb:933:in `dispatch!'
        d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:923:in `block in call!'
        d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `block in invoke'
        d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/sinatra-2.0.0/lib/sinatra/base.rb:1073:in `catch'
.... ...
```

my environments is:
padrino 0.13.3.2
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]

**Comment by adam12** [comment]
Updating your Padrino version should fix it. It's a few versions behind (latest is 0.14.1.1).

**Comment by jiyaping** [comment]
@adam12  for new create project, upgrade could work fine. I just upgrade an existed project to 0.14.1.1, and run padrino g admin -e erb  to recreate admin page, result in following erros:

```
E:\aocproject>padrino g admin -e erb
d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/padrino-admin-0.14.1.1/lib/padrino-admin/generators/actions.rb:75:in `scan': invalid byte sequence in GBK (ArgumentError)
        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/padrino-admin-0.14.1.1/lib/padrino-admin/generators/actions.rb:75:in `fetch_app_name'
        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/padrino-admin-0.14.1.1/lib/padrino-admin/generators/admin_app.rb:57:in `create_admin'
        from d:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
```

Is there any solutions? 

Thank for your help.

**Comment by adam12** [comment]
There were some encoding changes in 0.14.0 that could be related, but I'm not sure of the details.

I suggest closing this issue, and opening a new one for your most recent error, and maybe @ujifgc will have a suggestion on how to fix, as he implemented the encoding changes.

**Comment by jiyaping** [comment]
@adam12   Got it, Thanks.
