### ISSUE TITLE
Weirdness in Resolv.getaddress

### ISSUE THREAD

**Issue by thesp0nge** [padrino/padrino-framework#2159]
#### What is the current behavior?
The problem is in DNS resolution and the different behaviour is, on the same machine, same RVM environment, between padrino in console and irb when calling Resolv.getaddress

From within a padrino console session, a DNS resolution went in timeout

```
2.4.0 :012 > Resolv.getaddress('www.google.it')
Resolv::ResolvError: no address for www.google.it
	from /Users/thesp0nge/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/resolv.rb:95:in `getaddress'
	from /Users/thesp0nge/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/resolv.rb:45:in `getaddress'
	from (irb):12
	from /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/gems/padrino-core-0.14.1.1/lib/padrino-core/cli/base.rb:43:in `console'
	from /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/gems/padrino-core-0.14.1.1/bin/padrino:9:in `<top (required)>'
	from /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/bin/padrino:22:in `load'
	from /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/bin/padrino:22:in `<main>'
	from /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/bin/ruby_executable_hooks:15:in `eval'
	from /Users/thesp0nge/.rvm/gems/ruby-2.4.0@engage/bin/ruby_executable_hooks:15:in `<main>'
```

From an IRB session, same ruby version, same gemset, same machine, I've got and immediate resolution :
```
2.4.0 :004 > d.getaddress('www.google.it')
 => "172.217.19.131"
```

#### What is the expected behavior?
Also in Padrino, the address should be resolved

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? 
```
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
Padrino v. 0.14.1.1
sinatra 2.0.0
Rack 1.3 (Release: 2.0.3)
Darwin pollon 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

**Comment by adam12** [comment]
Why are you using `d.getaddress('www.google.it')` in the second example? What is `d`?

I don't think this is a Padrino issue. Is this a new Padrino app with no modifications?

```
$ padrino c
=> Loading development console (Padrino v.0.14.1.1)
=> Loading Application Foobar::App
irb(main):001:0> require "resolv"
=> true
irb(main):002:0> Resolv.getaddress('www.google.it')
=> "74.125.202.94"
```

**Comment by thesp0nge** [comment]
Hi @adam12 sorry, d was a Resolv::Dns.new object.

Here you can find an irb session.
```
2.4.0 :001 > require 'resolv'
 => true
2.4.0 :002 > Resolv.getaddress('www.google.it')
 => "172.217.19.131"
```

It's not a new Padrino app... it's a big multi application portal.
It's too weird something stucking DNS resolution... any idea if not padrino?

**Comment by adam12** [comment]
Can you post the application's Gemfile?

**Comment by thesp0nge** [comment]
```
source 'https://rubygems.org'

# Project requirements
gem 'rake'
gem 'sinatra-flash', :require => 'sinatra/flash'

gem "capistrano", "~> 2.15.5"
gem 'ipaddress'

gem 'bcrypt'
# gem "bcrypt-ruby", :require => "bcrypt"

# Component requirements
gem 'haml'
gem "pony", "~> 1.6.2"

gem 'net-ldap' 
gem 'puma'

gem 'dm-postgres-adapter'
gem 'dm-aggregates'
gem 'dm-validations'
gem 'dm-timestamps'
gem 'dm-migrations'
gem 'dm-constraints'
gem 'dm-core', '~>1.2.0'
gem 'dm-types'
gem 'dm-serializer'
gem 'dm-ar-finders'

gem 'will_paginate', '~> 3.0'
gem "nexpose"
gem "nexty", :group=>"development", :git=>"https://github.com/thesp0nge/nexty.git"
gem "trimmy", :git=>"https://github.com/thesp0nge/trimmy.git"
# gem "fastercsv"
# Test requirements
gem 'rspec-padrino', :group => "test"
gem 'rspec', :group => "test"
gem 'dm-rspec', :group => "test"
gem 'capybara', :group => "test"
gem 'cucumber', :group => "test"
gem 'factory_girl', :group => "test"
gem 'rack-test', :require => "rack/test"#, :group => "test"

gem 'rack-ssl', :group => ['test', 'production']
# Padrino Stable Gem
gem "padrino"

gem 'spreadsheet'
gem 'sanitize'
gem 'dawnscanner', :group => "development"
```

**Comment by adam12** [comment]
Nothing super exciting in there.

Any references to `Resolv` in your application? Perhaps in an initializer? Maybe someone manually set nameserver IPs.

**Comment by ujifgc** [comment]
Does not look like a Padrino issue.
