### ISSUE TITLE
bug: orm.rb throws an error upon admin_page generation

### ISSUE THREAD

**Issue by mistergibson** [padrino/padrino-framework#2192]
Reproduce:

padrino generate admin_page Counties
       exist  admin/views/counties
   identical  admin/controllers/counties.rb
Traceback (most recent call last):
	35: from /var/lib/gems/2.5.0/gems/padrino-gen-0.14.3/bin/padrino-gen:16:in `<main>'
	34: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	33: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
	32: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
	31: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
	30: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
	29: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
	28: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	27: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	26: from /var/lib/gems/2.5.0/gems/padrino-gen-0.14.3/lib/padrino-gen/generators/cli.rb:50:in `setup'
	25: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	24: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
	23: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
	22: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
	21: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
	20: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
	19: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	18: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	17: from /var/lib/gems/2.5.0/gems/padrino-admin-0.14.3/lib/padrino-admin/generators/admin_page.rb:49:in `create_controller'
	16: from /var/lib/gems/2.5.0/gems/padrino-admin-0.14.3/lib/padrino-admin/generators/admin_page.rb:49:in `each'
	15: from /var/lib/gems/2.5.0/gems/padrino-admin-0.14.3/lib/padrino-admin/generators/admin_page.rb:55:in `block in create_controller'
	14: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/file_manipulation.rb:119:in `template'
	13: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:25:in `create_file'
	12: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions.rb:94:in `action'
	11: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:60:in `invoke!'
	10: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/empty_directory.rb:115:in `invoke_with_conflict_check'
	 9: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:73:in `on_conflict_behavior'
	 8: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:46:in `identical?'
	 7: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/create_file.rb:53:in `render'
	 6: from /var/lib/gems/2.5.0/gems/thor-0.20.0/lib/thor/actions/file_manipulation.rb:122:in `block in template'
	 5: from /usr/lib/ruby/2.5.0/erb.rb:876:in `result'
	 4: from /usr/lib/ruby/2.5.0/erb.rb:876:in `eval'
	 3: from /var/lib/gems/2.5.0/gems/padrino-admin-0.14.3/lib/padrino-admin/generators/templates/haml/page/_form.haml.tt:1:in `template'
	 2: from /var/lib/gems/2.5.0/gems/padrino-admin-0.14.3/lib/padrino-admin/generators/orm.rb:91:in `column_fields'
	 1: from /var/lib/gems/2.5.0/gems/padrino-admin-0.14.3/lib/padrino-admin/generators/orm.rb:91:in `reject!'
/var/lib/gems/2.5.0/gems/padrino-admin-0.14.3/lib/padrino-admin/generators/orm.rb:91:in `block in column_fields': undefined method `name' for :id:Symbol (NoMethodError)
 

#### What is the expected behavior?

generate my scaffolding without error like it did all the others.

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

Ruby 2.5.0, Padrino 0.14.3, Sequel 5.10.0

This is the first Padrino (and accompanying gems) I've tried thus far.
This is the db/migration for the model in question:
Sequel.migration do
  up do
    create_table :counties do
      primary_key :id
      String :state_uuid
      String :uuid
      String :name
    end
  end

  down do
    drop_table :counties
  end
end

**Comment by mistergibson** [comment]
Note: when I altered the name of the field to 'title' instead of 'name' it worked as expected.
