### ISSUE TITLE
Problem with url(...) with multiple matched routes

### ISSUE THREAD

**Issue by takeshi-yashiro** [padrino/padrino-framework#2219]
#### Do you want to request a *feature* or report a *bug*?

bug

#### What is the current behavior?

Assume we have the following controller:
``` ruby
bash-5.0# cat app/controllers/test.rb
Test::App.controllers :test do

  get :foo, with: [:one, :two] do
    "world"
  end

  get :foo, with: :one do
    "hello"
  end

end
```

`Test::App.url(:test, :foo, one: "one")` shall match the second route `with: :one`, not the first `with: [:one, :two]`. However, the first one is actually taken and thus raises an error like below:

``` ruby
bash-5.0# bundle exec padrino c
=> Loading development console (Padrino v.0.14.4)
=> Loading Application Test::App
irb(main):001:0> Test::App.url(:test, :foo, one: "one")
Traceback (most recent call last):
       16: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
       15: from /usr/local/bundle/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
       14: from /usr/local/bundle/gems/padrino-core-0.14.4/lib/padrino-core/cli/base.rb:43:in `console'
       13: from (irb):1
       12: from /usr/local/bundle/gems/padrino-core-0.14.4/lib/padrino-core/application/routing.rb:343:in `url'
       11: from /usr/local/bundle/gems/padrino-core-0.14.4/lib/padrino-core/application/routing.rb:432:in `make_path_with_params'
       10: from /usr/local/bundle/gems/padrino-core-0.14.4/lib/padrino-core/path_router.rb:70:in `path'
        9: from /usr/local/bundle/gems/padrino-core-0.14.4/lib/padrino-core/path_router/matcher.rb:44:in `expand'
        8: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/ast/pattern.rb:108:in `expand'
        7: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/expander.rb:152:in `expand'
        6: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/expander.rb:182:in `with_rest'
        5: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/expander.rb:150:in `expand'
        4: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/ast/expander.rb:97:in `expand'
        3: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/ast/expander.rb:97:in `fetch'
        2: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/ast/expander.rb:97:in `block in expand'
        1: from /usr/local/bundle/gems/mustermann-1.1.0/lib/mustermann/ast/expander.rb:120:in `error_for'
Mustermann::ExpandError (cannot expand with keys [:one], possible expansions: [:one, :two])
```

The following patch seems to solve the problem, although I'm not sure it is a perfect solution.
``` diff
bash-5.0# diff -u padrino-core-0.14.4/lib/padrino-core/path_router.rb.org padrino-core-0.14.4/lib/padrino-core/path_router.rb
--- padrino-core-0.14.4/lib/padrino-core/path_router.rb.org
+++ padrino-core-0.14.4/lib/padrino-core/path_router.rb
@@ -56,7 +56,7 @@
       #
       def path(name, *args)
         params = args.last.is_a?(Hash) ? args.pop : {}
-        candidates = @routes.select { |route| route.name == name }
+        candidates = @routes.select { |route| route.name == name && (route.matcher.names - params.keys.map(&:to_s)).length == 0 }
         fail InvalidRouteException if candidates.empty?
         route = candidates.sort_by! { |candidate|
           (params.keys.map(&:to_s) - candidate.matcher.names).length }.shift
```

#### What is the expected behavior?

```
irb(main):001:0> Test::App.url(:test, :foo, one: "one")
=> "/test/foo/one"
```

#### Which versions of Ruby, Padrino, Sinatra, Rack, OS are you using? Did this work in previous versions?

Ruby on Docker image `ruby:2.6-alpine` with Padrino 0.14.4

**Comment by takeshi-yashiro** [comment]
It seems that the problem is caused with `ruby:2.6-alpine`; the problem does not happen with `ruby:2.6-slim`
